"""Custom fields owned by Van Sales.

Two groups:

1. Van identity on Warehouse -- lets a warehouse be flagged as a van and carry
   its plate and default driver, so the app can name the van the rep is on.
2. Provenance on the documents the mobile app posts -- the client-generated
   UID that makes an offline replay idempotent, plus where the post happened.

``van_client_uid`` is unique on purpose. Frappe coerces an empty unique value
to NULL, so desk-created documents never collide, while a replayed offline
post hits a database-level unique key instead of creating a duplicate.
"""

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

# Documents the mobile app is allowed to create. Each gets the same
# provenance block so dedup and geo-stamping work identically everywhere.
POSTING_DOCTYPES = (
	"Sales Invoice",
	"Sales Order",
	"Payment Entry",
	"Delivery Note",
	"Material Request",
)


def _provenance_fields(insert_after: str) -> list[dict]:
	return [
		{
			"fieldname": "van_sales_section",
			"label": "Van Sales",
			"fieldtype": "Section Break",
			"insert_after": insert_after,
			"collapsible": 1,
		},
		{
			"fieldname": "van_client_uid",
			"label": "Client UID",
			"fieldtype": "Data",
			"insert_after": "van_sales_section",
			"read_only": 1,
			"unique": 1,
			"no_copy": 1,
			"print_hide": 1,
			"description": "Idempotency key generated by the mobile app before the document was queued.",
		},
		{
			"fieldname": "van_source",
			"label": "Posted From",
			"fieldtype": "Data",
			"insert_after": "van_client_uid",
			"read_only": 1,
			"no_copy": 1,
			"print_hide": 1,
		},
		{
			"fieldname": "van_sales_col",
			"fieldtype": "Column Break",
			"insert_after": "van_source",
		},
		{
			"fieldname": "van_latitude",
			"label": "Latitude",
			"fieldtype": "Float",
			"precision": "9",
			"insert_after": "van_sales_col",
			"read_only": 1,
			"no_copy": 1,
			"print_hide": 1,
		},
		{
			"fieldname": "van_longitude",
			"label": "Longitude",
			"fieldtype": "Float",
			"precision": "9",
			"insert_after": "van_latitude",
			"read_only": 1,
			"no_copy": 1,
			"print_hide": 1,
		},
		{
			"fieldname": "van_posted_at",
			"label": "Captured At",
			"fieldtype": "Datetime",
			"insert_after": "van_longitude",
			"read_only": 1,
			"no_copy": 1,
			"print_hide": 1,
			"description": "When the device captured the document, which may predate the sync.",
		},
	]


# Where the provenance section is anchored per doctype, so it lands after the
# main body rather than in the middle of the totals.
_ANCHORS = {
	"Sales Invoice": "is_return",
	"Sales Order": "order_type",
	"Payment Entry": "mode_of_payment",
	"Delivery Note": "is_return",
	"Material Request": "material_request_type",
}


def get_custom_fields() -> dict[str, list[dict]]:
	fields: dict[str, list[dict]] = {
		"Warehouse": [
			{
				"fieldname": "van_section",
				"label": "Van",
				"fieldtype": "Section Break",
				"insert_after": "warehouse_name",
			},
			{
				"fieldname": "is_van",
				"label": "Is a Van",
				"fieldtype": "Check",
				"insert_after": "van_section",
				"description": "Stock in this warehouse travels on a vehicle and is sold from it.",
			},
			{
				"fieldname": "vehicle",
				"label": "Vehicle",
				"fieldtype": "Link",
				"options": "Vehicle",
				"insert_after": "is_van",
				"depends_on": "eval:doc.is_van",
			},
			{
				"fieldname": "van_col",
				"fieldtype": "Column Break",
				"insert_after": "vehicle",
			},
			{
				"fieldname": "default_driver",
				"label": "Default Driver",
				"fieldtype": "Link",
				"options": "Driver",
				"insert_after": "van_col",
				"depends_on": "eval:doc.is_van",
			},
		]
	}

	# Reason code on a returned line. It is what decides whether the goods go
	# back into saleable van stock or into scrap, so it lives on the line
	# rather than the document -- one return can mix good and damaged stock.
	fields["Sales Invoice Item"] = [
		{
			"fieldname": "van_return_reason",
			"label": "Return Reason",
			"fieldtype": "Select",
			"options": "\ngood\ndamaged\nexpired",
			"insert_after": "warehouse",
			"depends_on": "eval:parent.is_return",
			"print_hide": 1,
		}
	]

	for doctype in POSTING_DOCTYPES:
		fields[doctype] = _provenance_fields(_ANCHORS[doctype])

	return fields


def create_van_sales_custom_fields() -> None:
	create_custom_fields(get_custom_fields(), ignore_validate=True)
	frappe.db.commit()
